name: Test and Upload Coverage to Coveralls

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and test
        run: ./gradlew test jacocoTestReport

      - name: Upload coverage to Coveralls
        uses:  coverallsapp/github-action@v2.3.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./build/reports/jacoco/test/jacocoTestReport.xml